kind: Service
apiVersion: v1
metadata:
  name: pingapp210
  labels:
    app: pingapp210
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  selector:
    app: pingapp210
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 4567